In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Load the raw CPI data
file_path_cpi = "/content/CPI-dataset - CPI.csv"
df_cpi = pd.read_csv(file_path_cpi, usecols=['date', 'division', 'index'])

In [3]:
# 2. View the first 5 rows of CPI data
df_cpi.head()

         date division  index
0  01/01/2000  overall   80.3
1  01/02/2000  overall   80.4
2  01/03/2000  overall   80.3
3  01/04/2000  overall   80.3
4  01/05/2000  overall   80.4

In [4]:
# 3. Filter only for the 'overall' division right from the start
df_cpi = df_cpi[df_cpi['division'] == 'overall'].copy()

In [5]:
# 4. Fix the date format dynamically using the Maximum trick
parsed_dates = pd.to_datetime(df_cpi['date'], format='mixed', dayfirst=True)
df_cpi['Year'] = parsed_dates.dt.year.astype(int)

In [6]:
# 5. Extract the true month by taking the max of the month
df_cpi['Month'] = np.maximum(parsed_dates.dt.month, parsed_dates.dt.day).astype(int)

In [7]:
# 6. Create our standard Master 'Date' column
df_cpi['Date'] = pd.to_datetime(df_cpi[['Year', 'Month']].assign(DAY=1))

In [8]:
# 7. Rename the original 'index' column to 'CPI_Index' to avoid confusion
df_cpi.rename(columns={'index': 'CPI_Index'}, inplace=True)

In [9]:
# 8. View the first 5 rows after fixing the date format , extracting the month , craeting date column
df_cpi.head()

         date division  CPI_Index  Year  Month       Date
0  01/01/2000  overall       80.3  2000      1 2000-01-01
1  01/02/2000  overall       80.4  2000      2 2000-02-01
2  01/03/2000  overall       80.3  2000      3 2000-03-01
3  01/04/2000  overall       80.3  2000      4 2000-04-01
4  01/05/2000  overall       80.4  2000      5 2000-05-01

In [10]:
# 9. Keep only the necessary columns
df_cpi_clean = df_cpi[['Date', 'Year', 'Month', 'CPI_Index']].copy()

In [11]:
# 10. View the first 5 rows after selecting necessary columns only
df_cpi_clean.head()

        Date  Year  Month  CPI_Index
0 2000-01-01  2000      1       80.3
1 2000-02-01  2000      2       80.4
2 2000-03-01  2000      3       80.3
3 2000-04-01  2000      4       80.3
4 2000-05-01  2000      5       80.4

In [12]:
# 11. Filter strictly for the 2013 to 2026 timeframe and sort chronologically
df_cpi_clean = df_cpi_clean[(df_cpi_clean['Date'] >= '2013-01-01') & (df_cpi_clean['Date'] <= '2026-01-01')].reset_index(drop=True)
df_cpi_clean = df_cpi_clean.sort_values(by='Date').reset_index(drop=True)

In [13]:
print("CPI Data (First 5 Rows):")
print(df_cpi_clean.head())
print("\nCPI Data (Last 5 Rows):")
print(df_cpi_clean.tail())
print(f"\nTotal Rows: {len(df_cpi_clean)}")

CPI Data (First 5 Rows):
        Date  Year  Month  CPI_Index
0 2013-01-01  2013      1      105.9
1 2013-02-01  2013      2      106.1
2 2013-03-01  2013      3      106.2
3 2013-04-01  2013      4      106.3
4 2013-05-01  2013      5      106.6

CPI Data (Last 5 Rows):
          Date  Year  Month  CPI_Index
152 2025-09-01  2025      9      135.2
153 2025-10-01  2025     10      135.1
154 2025-11-01  2025     11      135.1
155 2025-12-01  2025     12      135.5
156 2026-01-01  2026      1      135.7

Total Rows: 157