In [56]:
import pandas as pd
import numpy as np

In [57]:
# 1. Load the raw Exchange Rate data (without headers so we can count columns easily)
file_path_ex = "/content/Exchange-dataset - Exchange rate.csv"
df_ex = pd.read_csv(file_path_ex, header=None)

In [58]:
# 2. Extract Column 1 (Year), Column 2 (Month), and Column 16 (USD Average)
df_ex_clean = df_ex.iloc[:, [0, 1, 15]].copy()
df_ex_clean.columns = ['Year', 'Month', 'USD_Avg']

In [59]:
# 3. View the first 5 rows of Exchange data
df_ex_clean.head()

     Year Month USD_Avg
0     2.6   NaN     NaN
1     NaN   NaN     NaN
2     NaN   NaN     NaN
3  Tempoh   NaN     NaN
4     NaN   NaN     USD

In [60]:
# 4. Convert Year and Month to numbers (this turns any text headers into NaN)
df_ex_clean['Year'] = pd.to_numeric(df_ex_clean['Year'], errors='coerce')
df_ex_clean['Month'] = pd.to_numeric(df_ex_clean['Month'], errors='coerce')

In [61]:
# 5. View the first 5 rows of Exchange data
df_ex_clean.head()

   Year  Month USD_Avg
0   2.6    NaN     NaN
1   NaN    NaN     NaN
2   NaN    NaN     NaN
3   NaN    NaN     NaN
4   NaN    NaN     USD

In [62]:
# 6. Drop rows where the Month is NaN (This perfectly removes the annual averages at the top of the file)
df_ex_clean = df_ex_clean.dropna(subset=['Month'])

In [63]:
# 7. View the first 5 rows of Exchange data after dropping rows where the Month is NAN
df_ex_clean.head()

      Year  Month USD_Avg
63  1997.0    1.0   2.491
64     NaN    2.0   2.486
65     NaN    3.0  2.4769
66     NaN    4.0   2.501
67     NaN    5.0   2.507

In [64]:
# 8. Forward-fill the Year column down across the empty months
df_ex_clean['Year'] = df_ex_clean['Year'].ffill()

In [65]:
# 9. View the first 5 rows of Exchange data after forward fill of year
df_ex_clean.head()

      Year  Month USD_Avg
63  1997.0    1.0   2.491
64  1997.0    2.0   2.486
65  1997.0    3.0  2.4769
66  1997.0    4.0   2.501
67  1997.0    5.0   2.507

In [66]:
# 10. Convert to clean numbers
df_ex_clean['Year'] = df_ex_clean['Year'].astype(int)
df_ex_clean['Month'] = df_ex_clean['Month'].astype(int)
df_ex_clean['USD_Avg'] = pd.to_numeric(df_ex_clean['USD_Avg'], errors='coerce')

In [67]:
# 11. View the first and last 5 rows of Exchange data
print(df_ex_clean.head())
print(df_ex_clean.tail())

    Year  Month  USD_Avg
63  1997      1   2.4910
64  1997      2   2.4860
65  1997      3   2.4769
66  1997      4   2.5010
67  1997      5   2.5070
     Year  Month  USD_Avg
410  2025     12   4.0919
411  2026      1   4.0283
412  2026      2   3.9146
415  2026      1      NaN
418  2026      2      NaN

In [68]:
# 12. Drop footnote rows at the very bottom of the file that lack actual exchange rates
df_ex_clean = df_ex_clean.dropna(subset=['USD_Avg'])

In [69]:
# 13. View the first and last 5 rows of Exchange data after dropping footnote
print(df_ex_clean.head())
print(df_ex_clean.tail())

    Year  Month  USD_Avg
63  1997      1   2.4910
64  1997      2   2.4860
65  1997      3   2.4769
66  1997      4   2.5010
67  1997      5   2.5070
     Year  Month  USD_Avg
408  2025     10   4.2160
409  2025     11   4.1559
410  2025     12   4.0919
411  2026      1   4.0283
412  2026      2   3.9146

In [70]:
# 14. Create standard Master 'Date' column
df_ex_clean['Date'] = pd.to_datetime(df_ex_clean[['Year', 'Month']].assign(DAY=1))

In [71]:
# 15. Filter strictly for the 2013 to 2026 timeframe
df_ex_clean = df_ex_clean[(df_ex_clean['Date'] >= '2013-01-01') & (df_ex_clean['Date'] <= '2026-01-01')].reset_index(drop=True)

In [72]:
# 16. View the first and last 5 rows of Exchange data after setting timeframe
print(df_ex_clean.head())
print(df_ex_clean.tail())

   Year  Month  USD_Avg       Date
0  2013      1   3.0390 2013-01-01
1  2013      2   3.0978 2013-02-01
2  2013      3   3.1076 2013-03-01
3  2013      4   3.0498 2013-04-01
4  2013      5   3.0168 2013-05-01
     Year  Month  USD_Avg       Date
152  2025      9   4.2126 2025-09-01
153  2025     10   4.2160 2025-10-01
154  2025     11   4.1559 2025-11-01
155  2025     12   4.0919 2025-12-01
156  2026      1   4.0283 2026-01-01

In [73]:
# 17. Keep essential columns and rename Date for merging
df_ex_clean = df_ex_clean[['Date', 'Year', 'Month', 'USD_Avg']]

In [74]:
print("Exchange Data (First 5 Rows):")
print(df_ex_clean.head())
print("\nExchange Data (Last 5 Rows):")
print(df_ex_clean.tail())
print(f"\nTotal Rows: {len(df_ex_clean)}")

Exchange Data (First 5 Rows):
        Date  Year  Month  USD_Avg
0 2013-01-01  2013      1   3.0390
1 2013-02-01  2013      2   3.0978
2 2013-03-01  2013      3   3.1076
3 2013-04-01  2013      4   3.0498
4 2013-05-01  2013      5   3.0168

Exchange Data (Last 5 Rows):
          Date  Year  Month  USD_Avg
152 2025-09-01  2025      9   4.2126
153 2025-10-01  2025     10   4.2160
154 2025-11-01  2025     11   4.1559
155 2025-12-01  2025     12   4.0919
156 2026-01-01  2026      1   4.0283

Total Rows: 157

In [75]:
df_ex_clean = df_ex_clean.dropna()
print("DataFrame after dropping rows with null values:")
print(df_ex_clean.head())
print(f"Total Rows after dropping nulls: {len(df_ex_clean)}")

DataFrame after dropping rows with null values:
        Date  Year  Month  USD_Avg
0 2013-01-01  2013      1   3.0390
1 2013-02-01  2013      2   3.0978
2 2013-03-01  2013      3   3.1076
3 2013-04-01  2013      4   3.0498
4 2013-05-01  2013      5   3.0168
Total Rows after dropping nulls: 157