In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Load the raw M3 data
file_path_m3 = "/content/M3-dataset - M3.csv"

In [7]:
# 2. We skip the first 6 messy header rows and only take Column 0 (Year), 1 (Month), and 2 (Total M3)
df_m3 = pd.read_csv(file_path_m3, usecols=[0, 1, 2], skiprows=6, header=None)
df_m3.columns = ['Year', 'Month', 'M3_Total']

In [8]:
# 3. View the first 5 rows of M3 data
df_m3.head()

     Year  Month      M3_Total
0  2013.0      1  1,375,858.00
1     NaN      2  1,379,389.60
2     NaN      3  1,392,122.90
3     NaN      4  1,399,798.90
4     NaN      5  1,414,632.10

In [9]:
# 4. Clean the Year column and forward-fill the empty blanks
df_m3['Year'] = pd.to_numeric(df_m3['Year'], errors='coerce').ffill()

In [10]:
# 5. View the first 5 rows of M3 data
df_m3.head()

     Year  Month      M3_Total
0  2013.0      1  1,375,858.00
1  2013.0      2  1,379,389.60
2  2013.0      3  1,392,122.90
3  2013.0      4  1,399,798.90
4  2013.0      5  1,414,632.10

In [11]:
# 6. Clean the Month column and drop any purely text/empty rows
df_m3['Month'] = pd.to_numeric(df_m3['Month'], errors='coerce')
df_m3 = df_m3.dropna(subset=['Month'])

In [12]:
# 7. Clean the M3 values (in case any numbers were read as strings with commas)
if df_m3['M3_Total'].dtype == 'O':
    df_m3['M3_Total'] = df_m3['M3_Total'].str.replace(',', '')
df_m3['M3_Total'] = pd.to_numeric(df_m3['M3_Total'], errors='coerce')

In [13]:
# 8. Convert Year and Month to clean integers
df_m3['Year'] = df_m3['Year'].astype(int)
df_m3['Month'] = df_m3['Month'].astype(int)

In [14]:
# 9. View the first 5 rows of M3 data after column's data type change
df_m3.head()

   Year  Month   M3_Total
0  2013      1  1375858.0
1  2013      2  1379389.6
2  2013      3  1392122.9
3  2013      4  1399798.9
4  2013      5  1414632.1

In [15]:
# 10. Create our 'Date' column for merging
df_m3['Date'] = pd.to_datetime(df_m3[['Year', 'Month']].assign(DAY=1))

In [16]:
# 11. Filter strictly for 2013 to 2026 timeframe
df_m3_clean = df_m3[(df_m3['Date'] >= '2013-01-01') & (df_m3['Date'] <= '2026-01-01')].copy()

In [17]:
# 12. Keep only the essential columns to merge later
df_m3_clean = df_m3_clean[['Date', 'Year', 'Month', 'M3_Total']].reset_index(drop=True)

In [18]:
print("M3 Data (First 5 Rows):")
print(df_m3_clean.head())
print("\nM3 Data (Last 5 Rows):")
print(df_m3_clean.tail())
print(f"\nTotal Rows: {len(df_m3_clean)}")

M3 Data (First 5 Rows):
        Date  Year  Month   M3_Total
0 2013-01-01  2013      1  1375858.0
1 2013-02-01  2013      2  1379389.6
2 2013-03-01  2013      3  1392122.9
3 2013-04-01  2013      4  1399798.9
4 2013-05-01  2013      5  1414632.1

M3 Data (Last 5 Rows):
          Date  Year  Month   M3_Total
152 2025-09-01  2025      9  2522834.6
153 2025-10-01  2025     10  2546954.1
154 2025-11-01  2025     11  2550062.5
155 2025-12-01  2025     12  2591321.8
156 2026-01-01  2026      1  2578208.9

Total Rows: 157