In [ ]:
import pandas as pd
import numpy as np

In [2]:
# 1. Load the raw unemployment data
file_path_unemp = "/content/Unemployment-dataset - Unemployment.csv"
df_unemp = pd.read_csv(file_path_unemp, usecols=['date', 'u_rate'])

In [3]:
# 2. View the first 5 rows of unemployment data
df_unemp.head()

         date  u_rate
0  01/01/2010     3.5
1  01/02/2010     3.5
2  01/03/2010     3.5
3  01/04/2010     3.0
4  01/05/2010     3.3

In [4]:
# 3. Fix the date format dynamically using the Maximum trick
parsed_dates = pd.to_datetime(df_unemp['date'], format='mixed', dayfirst=True)
df_unemp['Year'] = parsed_dates.dt.year.astype(int)

In [5]:
# 4. Extract the true month by taking the maximum of the parsed month
df_unemp['Month'] = np.maximum(parsed_dates.dt.month, parsed_dates.dt.day).astype(int)

In [6]:
# 5. Create our standard Master 'Date' column (YYYY-MM-01)
df_unemp['Date'] = pd.to_datetime(df_unemp[['Year', 'Month']].assign(DAY=1))

In [7]:
# 6. View the first 5 rows of unemployment data after creating date column
df_unemp.head()

         date  u_rate  Year  Month       Date
0  01/01/2010     3.5  2010      1 2010-01-01
1  01/02/2010     3.5  2010      2 2010-02-01
2  01/03/2010     3.5  2010      3 2010-03-01
3  01/04/2010     3.0  2010      4 2010-04-01
4  01/05/2010     3.3  2010      5 2010-05-01

In [8]:
# 6. Filter strictly for the 2013 to 2026 Jan timeframe
df_unemp_clean = df_unemp[(df_unemp['Date'] >= '2013-01-01') & (df_unemp['Date'] <= '2026-01-01')].copy()

In [9]:
# 7. Keep only the essential columns
df_unemp_clean = df_unemp_clean[['Date', 'Year', 'Month', 'u_rate']].reset_index(drop=True)

In [10]:
# 8. View the first 5 rows of unemployment data after selecting necessary columns only
df_unemp_clean.head()

        Date  Year  Month  u_rate
0 2013-01-01  2013      1     3.4
1 2013-02-01  2013      2     3.0
2 2013-03-01  2013      3     3.2
3 2013-04-01  2013      4     3.0
4 2013-05-01  2013      5     3.2

In [11]:
# 9. Rename 'u_rate' to proper name
df_unemp_clean.rename(columns={'u_rate': 'Unemployment_Rate'}, inplace=True)

In [12]:
print("Unemployment Data (First 5 Rows):")
print(df_unemp_clean.head())
print("\nUnemployment Data (Last 5 Rows):")
print(df_unemp_clean.tail())
print(f"\nTotal Rows: {len(df_unemp_clean)}")

Unemployment Data (First 5 Rows):
        Date  Year  Month  Unemployment_Rate
0 2013-01-01  2013      1                3.4
1 2013-02-01  2013      2                3.0
2 2013-03-01  2013      3                3.2
3 2013-04-01  2013      4                3.0
4 2013-05-01  2013      5                3.2

Unemployment Data (Last 5 Rows):
          Date  Year  Month  Unemployment_Rate
152 2025-09-01  2025      9                3.0
153 2025-10-01  2025     10                3.0
154 2025-11-01  2025     11                2.9
155 2025-12-01  2025     12                2.9
156 2026-01-01  2026      1                2.9

Total Rows: 157

In [13]:
df_unemp_clean = df_unemp_clean.dropna()
print("DataFrame after dropping rows with null values:")
print(df_unemp_clean.head())
print(f"Total Rows after dropping nulls: {len(df_unemp_clean)}")

DataFrame after dropping rows with null values:
        Date  Year  Month  Unemployment_Rate
0 2013-01-01  2013      1                3.4
1 2013-02-01  2013      2                3.0
2 2013-03-01  2013      3                3.2
3 2013-04-01  2013      4                3.0
4 2013-05-01  2013      5                3.2
Total Rows after dropping nulls: 157